# Generated by Django 2.0.3 on 2018-03-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180325_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', '汉子'), ('F', '妹子')], default='F', max_length=10),
        ),
    ]
