# Generated by Django 2.0.3 on 2018-03-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180326_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', '汉子'), ('F', '妹子')], default='F', max_length=10),
        ),
    ]
