# Generated by Django 2.0.3 on 2018-03-18 20:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180319_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 20, 23, 41, 812400, tzinfo=utc)),
        ),
    ]
