# Generated by Django 2.0.3 on 2018-03-19 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180319_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 8, 56, 37, 641884, tzinfo=utc)),
        ),
    ]
