# Generated by Django 2.0.3 on 2018-03-25 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180319_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 25, 14, 25, 53, 768437, tzinfo=utc)),
        ),
    ]
