# Generated by Django 2.0.3 on 2018-03-26 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180325_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 7, 5, 58, 439026, tzinfo=utc)),
        ),
    ]
