# Generated by Django 2.0.3 on 2018-03-26 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20180326_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 13, 9, 29, 647856, tzinfo=utc)),
        ),
    ]
