# Generated by Django 2.0.3 on 2018-03-27 12:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20180327_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
