# Generated by Django 2.0.3 on 2018-03-27 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20180327_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default='请在此处填写活动简介'),
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='slug2',
            field=models.SlugField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='activity',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
