# Generated by Django 2.0.3 on 2018-03-30 14:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20180327_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('updated',)},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='slug2',
        ),
        migrations.AddField(
            model_name='activity',
            name='description2',
            field=models.TextField(default='请在此处填写活动简介，此简介将展示在活动列表页面'),
        ),
        migrations.AddField(
            model_name='activity',
            name='show2',
            field=models.IntegerField(choices=[(1, '是'), (2, '否')], default=1, verbose_name='是否显示在首页'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='请在此处添加具体文章'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='活动时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(default='请在此处填写活动简介，此简介将显示在首页'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='活动主图'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='show',
            field=models.IntegerField(choices=[(1, '当季热卖'), (2, '历史活动'), (3, '不显示在活动列表中')], default=1, verbose_name='活动类型'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, verbose_name='不用填写'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='url',
            field=models.URLField(blank=True, verbose_name='不用填写'),
        ),
    ]
